### ISSUE TITLE
Error when submitting simulation: AttributeError: RestartProperties instance has no attribute 'WallTime' (Trac #18)

### ISSUE THREAD

**Issue by riksanyal** [riksanyal/et#18]
After updating to revision 932, I now get the following error after the job starts:

Traceback (most recent call last):
  File "/home/ianhin/Cactus/llama/simfactory2/sim", line 159, in ?
    main(SimEnvironment)
  File "/home/ianhin/Cactus/llama/simfactory2/sim", line 151, in main
    CommandDispatch()
  File "/home/ianhin/Cactus/llama/simfactory2/sim", line 118, in CommandDispatch
    module.main(SimEnvironment)
  File "/home/ianhin/Cactus/llama/simfactory2/lib/modules/sim-manage.py", line 379, in main
    CommandDispatch()
  File "/home/ianhin/Cactus/llama/simfactory2/lib/modules/sim-manage.py", line 322, in CommandDispatch
    exec("command_%s()" % command)
  File "<string>", line 1, in ?
  File "/home/ianhin/Cactus/llama/simfactory2/lib/modules/sim-manage.py", line 197, in command_run
    restart.run()
  File "/home/ianhin/Cactus/llama/simfactory2/lib/simrestart.py", line 763, in run
    walltime_raw = self.Properties.WallTime
AttributeError: RestartProperties instance has no attribute 'WallTime'

Migrated from https://trac.einsteintoolkit.org/ticket/18
```json
{
    "status": "closed", 
    "changetime": "2010-10-08T18:35:13", 
    "description": "After updating to revision 932, I now get the following error after the job starts:\n\nTraceback (most recent call last):\n  File \"/home/ianhin/Cactus/llama/simfactory2/sim\", line 159, in ?\n    main(SimEnvironment)\n  File \"/home/ianhin/Cactus/llama/simfactory2/sim\", line 151, in main\n    CommandDispatch()\n  File \"/home/ianhin/Cactus/llama/simfactory2/sim\", line 118, in CommandDispatch\n    module.main(SimEnvironment)\n  File \"/home/ianhin/Cactus/llama/simfactory2/lib/modules/sim-manage.py\", line 379, in main\n    CommandDispatch()\n  File \"/home/ianhin/Cactus/llama/simfactory2/lib/modules/sim-manage.py\", line 322, in CommandDispatch\n    exec(\"command_%s()\" % command)\n  File \"<string>\", line 1, in ?\n  File \"/home/ianhin/Cactus/llama/simfactory2/lib/modules/sim-manage.py\", line 197, in command_run\n    restart.run()\n  File \"/home/ianhin/Cactus/llama/simfactory2/lib/simrestart.py\", line 763, in run\n    walltime_raw = self.Properties.WallTime\nAttributeError: RestartProperties instance has no attribute 'WallTime'\n", 
    "reporter": "hinder", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1286562913583223", 
    "component": "SimFactory", 
    "summary": "Error when submitting simulation: AttributeError: RestartProperties instance has no attribute 'WallTime'", 
    "priority": "major", 
    "keywords": "", 
    "version": "", 
    "time": "2010-10-08T16:55:26", 
    "milestone": "", 
    "owner": "mrthomas", 
    "type": "defect"
}
```

**Comment by riksanyal** [comment]
Trac update at 20101008T17:42:18: hinder commented:

> Problem started in revision 929: "add walltime properites if a walltime was specified when submitting"

**Comment by riksanyal** [comment]
Trac update at 20101008T18:34:34: hinder commented:

> Fixed in r934.

**Comment by riksanyal** [comment]
Trac update at 20101008T18:35:13: 
* hinder changed resolution from "" to "fixed"
* hinder changed status from "new" to "closed"
